refac: setup input fields for lock, add lock contract call
Token-Giver/token-giver pull request #72
Opened 2024-12-14 20:45 UTC by Samuel1-ona

I have made necessary changes as requested in #68

2024-12-16 11:32 UTC, Oshioke-Salaki commented
please fix merge conflicts

2024-12-17 07:43 UTC, stephanniegb commented
Thanks for your contributions! It looks great!

2024-12-17 07:58 UTC, stephanniegb requested changes

2024-12-17 07:58 UTC, stephanniegb commented on app/create/components/StepThree.tsx
> +      <label htmlFor="lockUntilTime">Lock Until: </label>
Make the look of the for match the others (bg color, text etc)

2024-12-17 07:58 UTC, stephanniegb commented on app/create/page.tsx
Since the lock function is optional, the `setLoadingPercentage` should to to 100 if the user is locking the campaign and if not.

2024-12-17 07:58 UTC, stephanniegb commented on app/create/components/StepThree.tsx
> +  const timezones = ["GMT", "UTC"];
It should be GMT or local time. Check out the unix time converter function in the in the helper folder `index.ts`

2024-12-17 07:58 UTC, stephanniegb commented on app/create/components/StepThree.tsx
> +  const timezones = ["GMT", "UTC"];
please resolve merge conflicts

2024-12-17 09:16 UTC, Samuel1-ona commented
Hi @stephanniegb and @Oshioke-Salaki , i have made requested changes

2024-12-17 10:44 UTC, stephanniegb requested changes

2024-12-17 10:44 UTC, stephanniegb commented on app/create/page.tsx
It `setLoadingPercentage` still does not get to 100 if i am not locking the campaign

2024-12-17 10:44 UTC, stephanniegb commented on app/create/components/StepThree.tsx
> +      <label htmlFor="lockUntilTime">Lock Until: </label>
BG color of input form is still wrong

2024-12-17 11:02 UTC, Samuel1-ona commented
Hi @stephanniegb , fixed it , made locktime optional if user doesnt set it

2024-12-17 14:32 UTC, stephanniegb commented
please resolve merge conflict

2024-12-17 14:45 UTC, merged