Mobile view of explore page
Token-Giver/token-giver pull request #78
Opened 2024-12-19 07:42 UTC by deeseeker

2024-12-21 19:42 UTC, stephanniegb commented
Hey, thanks for you contributions! It looks great

2024-12-21 19:43 UTC, stephanniegb commented
clicking the cards does nothing, it is supposed to link to the campaign detail page

2024-12-21 19:48 UTC, stephanniegb requested changes

2024-12-21 19:48 UTC, stephanniegb commented on public/kosuki.jpg
What are these images for? the cards in the figma are dummy cards and should not be added to the page

2024-12-21 19:48 UTC, stephanniegb commented on app/utils/explore-data.ts
there is no need for the dummy data, just use the campaigns  being returned from the endpoint

2024-12-21 19:54 UTC, stephanniegb commented
<img width="1470" alt="Screenshot 2024-12-21 at 8 52 14 PM" src="https://github.com/user-attachments/assets/2c220262-7e54-44b1-8821-912bc091ff53" />
<img width="1470" alt="Screenshot 2024-12-21 at 8 52 20 PM" src="https://github.com/user-attachments/assets/1a0cf532-3d69-46f7-b1a1-c80d4a8c2456" />
You are supposed to change the UI of the campaign cards, not create dummy campaigns.

2024-12-21 21:25 UTC, deeseeker commented on public/kosuki.jpg
I just came up with it through my initiative. I will factor in all the feedbacks. Sorry for the inconvenience

2024-12-22 12:27 UTC, stephanniegb commented
LFTM🚀. Thanks for your contribution✨

2024-12-22 12:27 UTC, merged